matrix:
- name: markdown
  pipeline:
  - pyspelling.filters.text
  sources:
  - '**/*.md'
  default_encoding: utf-8
- name: Quarto markdown
  pipeline:
  - pyspelling.filters.text
  sources:
  - '**/*.qmd'
  default_encoding: utf-8
