# Render Quarto presentations to PDF
name: Build PDFs

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"


jobs:
  check_links:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install Python packages
        run: pip install nbformat

      - uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: install.packages(c("testthat", "reticulate", "rmarkdown"))
        shell: Rscript {0}

      - uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
          path: tdd/tdd_lecture/netiquette.qmd

      - uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
          path: tdd/tdd_lecture/tdd_lecture.qmd

      - uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
          path: testing/testing_lecture/testing_lecture.qmd

      - uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
          path: data_structures/data_structres_lecture/data_structures_lecture.qmd

      - uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
          path: algorithms/algorithms_lecture/algorithms_lecture.qmd

      - uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
          path: optimisation/optimisation_lecture/optimisation_lecture.qmd

      #############################################
      # Upload
      #############################################
      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: all_presentations
          path: "**/*.pdf"
          if-no-files-found: error

