# Render Quarto presentations to PDF

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

name: build_pdfs

jobs:
  check_links:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: quarto-dev/quarto-actions/render@v2
        with:
          path: algorithms/algorithms_lecture

      - uses: quarto-dev/quarto-actions/render@v2
        with:
          path: tdd/tdd_1_lecture

      - name: Find the PDFs
        run: find . | egrep "pdf"
