# Render Quarto presentations to PDF

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

name: build_pdfs

jobs:
  check_links:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2


      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - uses: r-lib/actions/setup-r@v2

      - name: Install the rmarkdown and reticulate R packages
        run: install.packages(c("reticulate", "rmarkdown"))
        shell: Rscript {0}

      - uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
          path: algorithms/algorithms_lecture/algorithms_lecture.qmd

      - uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
          path: tdd/tdd_1_lecture/tdd_1_lecture.qmd

      - name: Find the PDFs
        run: find . | egrep "pdf"
